# Generated by Django 5.2.16 on 2026-07-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='Mot-clé')),
                ('date', models.DateField(verbose_name='Date')),
                ('score', models.PositiveSmallIntegerField(help_text='Score relatif de 0 à 100 fourni par Google Trends', verbose_name="Score d'intérêt")),
                ('region', models.CharField(default='SN', max_length=5, verbose_name='Région')),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends')], default='google_trends', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Collecté le')),
            ],
            options={
                'verbose_name': 'Tendance de recherche',
                'verbose_name_plural': 'Tendances de recherche',
                'ordering': ['-date', 'keyword'],
                'constraints': [models.UniqueConstraint(fields=('keyword', 'date', 'region', 'source'), name='unique_trend_record')],
            },
        ),
    ]
