# Generated by Django 5.2.16 on 2026-07-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('agriculture', 'Agriculture & Forêt'), ('elevage', 'Élevage (Animaux de ferme)')], db_index=True, max_length=50, verbose_name='Domaine')),
                ('query', models.CharField(db_index=True, max_length=255, verbose_name='Requête')),
                ('query_type', models.CharField(choices=[('top', 'Top recherches'), ('rising', 'En forte hausse')], max_length=10, verbose_name='Type')),
                ('value_display', models.CharField(max_length=50, verbose_name='Valeur Google')),
                ('region', models.CharField(default='SN', max_length=5, verbose_name='Région')),
                ('discovered_at', models.DateTimeField(auto_now=True, verbose_name='Découvert le')),
            ],
            options={
                'verbose_name': 'Requête découverte',
                'verbose_name_plural': 'Requêtes découvertes',
                'ordering': ['-discovered_at', 'domain', 'query_type'],
                'constraints': [models.UniqueConstraint(fields=('domain', 'query', 'query_type', 'region'), name='unique_discovered_query')],
            },
        ),
    ]
