# Generated by Django 5.2.16 on 2026-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_discoveredquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Identifiant')),
                ('label', models.CharField(max_length=120, verbose_name='Nom du domaine')),
                ('cat_id', models.PositiveIntegerField(verbose_name='Catégorie Google Trends (ID)')),
                ('seed_keywords', models.TextField(help_text='Séparez les mots-clés par des virgules.', verbose_name='Mots-clés de départ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Domaine de marché',
                'verbose_name_plural': 'Domaines de marché',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('today 1-m', 'Dernier mois'), ('today 3-m', '3 derniers mois'), ('today 12-m', '12 derniers mois')], default='today 3-m', max_length=20, verbose_name='Période')),
                ('region', models.CharField(default='SN', max_length=5, verbose_name='Région')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_domains', models.ManyToManyField(blank=True, related_name='discovery_configs', to='intelligence.marketdomain', verbose_name='Domaines sélectionnés')),
            ],
            options={
                'verbose_name': 'Configuration de découverte',
                'verbose_name_plural': 'Configuration de découverte',
            },
        ),
    ]
