# Generated by Django 5.2.16 on 2026-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_seed_market_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialScrapeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok')], db_index=True, max_length=20, verbose_name='Plateforme')),
                ('url', models.URLField(max_length=500, verbose_name='URL cible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('max_posts', models.PositiveSmallIntegerField(default=20, verbose_name='Max publications')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier scrape')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Cible réseau social',
                'verbose_name_plural': 'Cibles réseaux sociaux',
                'ordering': ['platform', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok')], db_index=True, max_length=20, verbose_name='Plateforme')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL source')),
                ('post_url', models.URLField(blank=True, max_length=500, verbose_name='URL publication')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='Auteur')),
                ('content', models.TextField(verbose_name='Contenu brut')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='Empreinte')),
                ('analysis_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Analysé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=12, verbose_name='Statut analyse')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Catégorie NLP')),
                ('sentiment', models.CharField(blank=True, max_length=20, verbose_name='Sentiment')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Mots-clés')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Collecté le')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analysé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Publication sociale',
                'verbose_name_plural': 'Publications sociales',
                'ordering': ['-scraped_at'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'content_hash'), name='unique_social_post_hash')],
            },
        ),
    ]
