# Generated by Django 5.2.16 on 2026-07-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0012_market_search_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
