# Generated by Django 5.2.16 on 2026-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0014_tiktok_scrape_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Commentaires (total plateforme)'),
        ),
    ]
