# Generated by Django 5.2.16 on 2026-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0015_alter_socialpost_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcomment',
            name='extracted_product',
            field=models.CharField(blank=True, db_index=True, help_text='Nom normalisé détecté (ex. motopompe, mini tracteur).', max_length=120, verbose_name='Produit extrait'),
        ),
        migrations.AddField(
            model_name='socialcomment',
            name='extracted_product_slug',
            field=models.SlugField(blank=True, max_length=80, verbose_name='Slug produit'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='extracted_product',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Produit principal'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='extracted_product_slug',
            field=models.SlugField(blank=True, max_length=80, verbose_name='Slug produit'),
        ),
        migrations.CreateModel(
            name='TopPurchaseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(db_index=True, verbose_name='Rang')),
                ('product_slug', models.SlugField(max_length=80, verbose_name='Slug produit')),
                ('product_name', models.CharField(max_length=120, verbose_name='Nom produit')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Catégorie métier')),
                ('score', models.FloatField(db_index=True, verbose_name='Score demande')),
                ('score_normalized', models.PositiveSmallIntegerField(default=0, help_text='Barre de progression UI.', verbose_name='Score affiché (0-100)')),
                ('purchase_intent_count', models.PositiveIntegerField(default=0, verbose_name="Intentions d'achat")),
                ('info_intent_count', models.PositiveIntegerField(default=0, verbose_name="Demandes d'info")),
                ('total_views', models.PositiveBigIntegerField(default=0, verbose_name='Vues cumulées')),
                ('trends_boost', models.FloatField(default=0, verbose_name='Bonus Google Trends')),
                ('related_posts', models.PositiveIntegerField(default=0, verbose_name='Publications liées')),
                ('evidence_text', models.CharField(blank=True, max_length=500, verbose_name='Preuve (résumé)')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Recommandation achat (Top 10)',
                'verbose_name_plural': 'Recommandations achat (Top 10)',
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('rank',), name='unique_top_purchase_rank')],
            },
        ),
    ]
