# Generated by Django 5.2.16 on 2026-07-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0019_jumia_marketplace_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumiaPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('old_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix barré (FCFA)')),
                ('discount_percent', models.FloatField(blank=True, null=True, verbose_name='Remise %')),
                ('stock_status', models.CharField(blank=True, max_length=20, verbose_name='Statut stock')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('is_in_stock', models.BooleanField(blank=True, null=True, verbose_name='En stock')),
                ('rating_value', models.FloatField(blank=True, null=True, verbose_name='Note')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Nb avis')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Capturé le')),
            ],
            options={
                'verbose_name': 'Snapshot prix Jumia',
                'verbose_name_plural': 'Snapshots prix Jumia',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug produit')),
                ('product_label', models.CharField(blank=True, max_length=120, verbose_name='Libellé')),
                ('avg_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix moyen marché')),
                ('min_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix min')),
                ('max_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix max')),
                ('avg_discount_percent', models.FloatField(blank=True, null=True, verbose_name='Remise moyenne %')),
                ('price_sample_size', models.PositiveIntegerField(default=0, verbose_name='Échantillon prix')),
                ('out_of_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs en rupture')),
                ('in_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs en stock')),
                ('low_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs stock faible')),
                ('stockout_rate', models.FloatField(default=0, verbose_name='Taux rupture 0-1')),
                ('stock_alert', models.CharField(blank=True, choices=[('', 'Aucune'), ('watch', 'À surveiller'), ('critical', 'Rupture critique')], db_index=True, default='', max_length=16, verbose_name='Alerte stock')),
                ('avg_rating', models.FloatField(blank=True, null=True, verbose_name='Note moyenne')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='Total avis')),
                ('review_neg_ratio', models.FloatField(default=0, verbose_name='Ratio avis négatifs')),
                ('top_failure_tags', models.JSONField(blank=True, default=list, verbose_name='Failles top')),
                ('jumia_boost', models.FloatField(default=0, verbose_name='Bonus score Top10')),
                ('evidence_text', models.CharField(blank=True, max_length=400, verbose_name='Preuve')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Signal marché produit',
                'verbose_name_plural': 'Signaux marché produits',
                'ordering': ['-jumia_boost', 'product_slug'],
            },
        ),
        migrations.CreateModel(
            name='TestJumiaPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('old_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix barré (FCFA)')),
                ('discount_percent', models.FloatField(blank=True, null=True, verbose_name='Remise %')),
                ('stock_status', models.CharField(blank=True, max_length=20, verbose_name='Statut stock')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('is_in_stock', models.BooleanField(blank=True, null=True, verbose_name='En stock')),
                ('rating_value', models.FloatField(blank=True, null=True, verbose_name='Note')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Nb avis')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Capturé le')),
            ],
            options={
                'verbose_name': 'Snapshot prix Jumia (test)',
                'verbose_name_plural': 'Snapshots prix Jumia (test)',
                'db_table': 'intelligence_test_jumia_price_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TestProductMarketSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug produit')),
                ('product_label', models.CharField(blank=True, max_length=120, verbose_name='Libellé')),
                ('avg_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix moyen marché')),
                ('min_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix min')),
                ('max_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix max')),
                ('avg_discount_percent', models.FloatField(blank=True, null=True, verbose_name='Remise moyenne %')),
                ('price_sample_size', models.PositiveIntegerField(default=0, verbose_name='Échantillon prix')),
                ('out_of_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs en rupture')),
                ('in_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs en stock')),
                ('low_stock_count', models.PositiveIntegerField(default=0, verbose_name='SKUs stock faible')),
                ('stockout_rate', models.FloatField(default=0, verbose_name='Taux rupture 0-1')),
                ('stock_alert', models.CharField(blank=True, choices=[('', 'Aucune'), ('watch', 'À surveiller'), ('critical', 'Rupture critique')], db_index=True, default='', max_length=16, verbose_name='Alerte stock')),
                ('avg_rating', models.FloatField(blank=True, null=True, verbose_name='Note moyenne')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='Total avis')),
                ('review_neg_ratio', models.FloatField(default=0, verbose_name='Ratio avis négatifs')),
                ('top_failure_tags', models.JSONField(blank=True, default=list, verbose_name='Failles top')),
                ('jumia_boost', models.FloatField(default=0, verbose_name='Bonus score Top10')),
                ('evidence_text', models.CharField(blank=True, max_length=400, verbose_name='Preuve')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Signal marché (test)',
                'verbose_name_plural': 'Signaux marché (test)',
                'db_table': 'intelligence_test_product_market_signal',
                'ordering': ['-jumia_boost', 'product_slug'],
            },
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='aspect_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Résumé aspects'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='catalog_product_slug',
            field=models.SlugField(blank=True, max_length=80, verbose_name='Slug catalogue YAYEMATY'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='discount_percent',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Remise %'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='is_in_stock',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='En stock'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='nlp_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NLP le'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='sentiment_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Résumé sentiment'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='stock_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stock vérifié le'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Ex. « Il n'en reste plus que X ».", null=True, verbose_name='Quantité restante'),
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=20, verbose_name='Statut stock'),
        ),
        migrations.AddField(
            model_name='jumiareview',
            name='aspect_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance aspects'),
        ),
        migrations.AddField(
            model_name='jumiareview',
            name='aspects',
            field=models.JSONField(blank=True, default=dict, help_text='Ex. {"qualite": "neg", "livraison": "neg", "prix": "pos"}', verbose_name='Aspects détectés'),
        ),
        migrations.AddField(
            model_name='jumiareview',
            name='failure_tags',
            field=models.JSONField(blank=True, default=list, help_text='Ex. ["fragile", "panne", "livraison_retard"]', verbose_name='Tags de failles'),
        ),
        migrations.AddField(
            model_name='jumiareview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positif'), ('negative', 'Négatif'), ('neutral', 'Neutre')], db_index=True, max_length=16, verbose_name='Sentiment'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='aspect_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Résumé aspects'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='catalog_product_slug',
            field=models.SlugField(blank=True, max_length=80, verbose_name='Slug catalogue'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='discount_percent',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Remise %'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='is_in_stock',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='En stock'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='nlp_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NLP le'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='sentiment_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Résumé sentiment'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='stock_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stock vérifié le'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité restante'),
        ),
        migrations.AddField(
            model_name='testjumiaproduct',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=20, verbose_name='Statut stock'),
        ),
        migrations.AddField(
            model_name='testjumiareview',
            name='aspect_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance aspects'),
        ),
        migrations.AddField(
            model_name='testjumiareview',
            name='aspects',
            field=models.JSONField(blank=True, default=dict, verbose_name='Aspects détectés'),
        ),
        migrations.AddField(
            model_name='testjumiareview',
            name='failure_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Tags de failles'),
        ),
        migrations.AddField(
            model_name='testjumiareview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positif'), ('negative', 'Négatif'), ('neutral', 'Neutre')], db_index=True, max_length=16, verbose_name='Sentiment'),
        ),
        migrations.AddField(
            model_name='testtoppurchaserecommendation',
            name='avg_market_price_xof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix moyen marché Jumia'),
        ),
        migrations.AddField(
            model_name='testtoppurchaserecommendation',
            name='jumia_boost',
            field=models.FloatField(default=0, verbose_name='Bonus Jumia'),
        ),
        migrations.AddField(
            model_name='testtoppurchaserecommendation',
            name='jumia_evidence',
            field=models.CharField(blank=True, max_length=300, verbose_name='Preuve Jumia'),
        ),
        migrations.AddField(
            model_name='testtoppurchaserecommendation',
            name='stock_alert',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Alerte stock Jumia'),
        ),
        migrations.AddField(
            model_name='toppurchaserecommendation',
            name='avg_market_price_xof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix moyen marché Jumia'),
        ),
        migrations.AddField(
            model_name='toppurchaserecommendation',
            name='jumia_boost',
            field=models.FloatField(default=0, verbose_name='Bonus Jumia'),
        ),
        migrations.AddField(
            model_name='toppurchaserecommendation',
            name='jumia_evidence',
            field=models.CharField(blank=True, max_length=300, verbose_name='Preuve Jumia'),
        ),
        migrations.AddField(
            model_name='toppurchaserecommendation',
            name='stock_alert',
            field=models.CharField(blank=True, default='', help_text='watch | critical | vide', max_length=16, verbose_name='Alerte stock Jumia'),
        ),
        migrations.AlterField(
            model_name='jumiaproduct',
            name='availability',
            field=models.CharField(blank=True, max_length=80, verbose_name='Disponibilité brute'),
        ),
        migrations.AlterField(
            model_name='jumiaproduct',
            name='old_price_xof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix barré (FCFA)'),
        ),
        migrations.AlterField(
            model_name='testjumiaproduct',
            name='availability',
            field=models.CharField(blank=True, max_length=80, verbose_name='Disponibilité brute'),
        ),
        migrations.AlterField(
            model_name='testjumiaproduct',
            name='old_price_xof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix barré (FCFA)'),
        ),
        migrations.AddIndex(
            model_name='jumiaproduct',
            index=models.Index(fields=['stock_status', '-rating_count'], name='intelligenc_stock_s_969a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='jumiaproduct',
            index=models.Index(fields=['catalog_product_slug', '-price_xof'], name='intelligenc_catalog_cadd17_idx'),
        ),
        migrations.AddField(
            model_name='jumiapricesnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='intelligence.jumiaproduct', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='testjumiapricesnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='intelligence.testjumiaproduct', verbose_name='Produit'),
        ),
        migrations.AddIndex(
            model_name='jumiapricesnapshot',
            index=models.Index(fields=['product', '-captured_at'], name='intelligenc_product_894b01_idx'),
        ),
    ]
