# Generated by Django 5.2.16 on 2026-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0020_jumia_market_intelligence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsearchkeyword',
            name='max_comments',
            field=models.PositiveSmallIntegerField(default=20, help_text='TikTok : commentaires/vidéo. Jumia : avis/produit (10–20 pour NLP).', verbose_name='Commentaires / avis'),
        ),
        migrations.AlterField(
            model_name='marketsearchkeyword',
            name='max_videos',
            field=models.PositiveSmallIntegerField(default=15, help_text='TikTok : vidéos. Jumia : produits scrapés pour ce mot-clé.', verbose_name='Max vidéos TikTok / produits Jumia'),
        ),
    ]
