# Generated by Django 5.2.16 on 2026-07-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0021_jumia_keyword_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestJijiListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='ID annonce')),
                ('listing_url', models.URLField(max_length=500, verbose_name='URL annonce')),
                ('title', models.CharField(max_length=400, verbose_name='Titre')),
                ('category', models.CharField(blank=True, max_length=160, verbose_name='Catégorie')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('is_negotiable', models.BooleanField(db_index=True, default=False, verbose_name='Négociable')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('used', 'Occasion'), ('refurbished', 'Reconditionné'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=20, verbose_name='État')),
                ('location_region', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Région')),
                ('location_area', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Quartier / zone')),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Vues')),
                ('seller_name', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='Vendeur')),
                ('seller_member_since', models.CharField(blank=True, max_length=80, verbose_name='Ancienneté vendeur')),
                ('seller_is_verified', models.BooleanField(default=False, verbose_name='Vendeur vérifié')),
                ('seller_is_premium', models.BooleanField(default=False, verbose_name='Vendeur premium')),
                ('seller_response_stat', models.CharField(blank=True, max_length=120, verbose_name='Réactivité vendeur')),
                ('seller_ads_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Annonces vendeur (estim.)')),
                ('search_keyword', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Mot-clé source')),
                ('catalog_product_slug', models.SlugField(blank=True, max_length=80, verbose_name='Slug catalogue YAYEMATY')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Attributs')),
                ('phone_revealed', models.BooleanField(default=False, verbose_name='Contact révélé')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Scrapé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Annonce Jiji (test)',
                'verbose_name_plural': 'Annonces Jiji (test)',
                'db_table': 'intelligence_test_jiji_listing',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='JijiListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='ID annonce')),
                ('listing_url', models.URLField(max_length=500, verbose_name='URL annonce')),
                ('title', models.CharField(max_length=400, verbose_name='Titre')),
                ('category', models.CharField(blank=True, max_length=160, verbose_name='Catégorie')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('is_negotiable', models.BooleanField(db_index=True, default=False, verbose_name='Négociable')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='Devise')),
                ('condition', models.CharField(choices=[('new', 'Neuf'), ('used', 'Occasion'), ('refurbished', 'Reconditionné'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=20, verbose_name='État')),
                ('location_region', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Région')),
                ('location_area', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Quartier / zone')),
                ('views_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Vues')),
                ('seller_name', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='Vendeur')),
                ('seller_member_since', models.CharField(blank=True, max_length=80, verbose_name='Ancienneté vendeur')),
                ('seller_is_verified', models.BooleanField(default=False, verbose_name='Vendeur vérifié')),
                ('seller_is_premium', models.BooleanField(default=False, verbose_name='Vendeur premium')),
                ('seller_response_stat', models.CharField(blank=True, max_length=120, verbose_name='Réactivité vendeur')),
                ('seller_ads_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Annonces vendeur (estim.)')),
                ('search_keyword', models.CharField(blank=True, db_index=True, help_text='Mot-clé MarketSearchKeyword ayant conduit à cette annonce.', max_length=120, verbose_name='Mot-clé source')),
                ('catalog_product_slug', models.SlugField(blank=True, max_length=80, verbose_name='Slug catalogue YAYEMATY')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Image')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Attributs')),
                ('phone_revealed', models.BooleanField(default=False, help_text='True uniquement si JIJI_REVEAL_CONTACTS activé (limite IP Jiji).', verbose_name='Contact révélé')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Scrapé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Annonce Jiji',
                'verbose_name_plural': 'Annonces Jiji',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['search_keyword', '-views_count'], name='intelligenc_search__3d6b78_idx'), models.Index(fields=['condition', '-price_xof'], name='intelligenc_conditi_4fef1b_idx'), models.Index(fields=['catalog_product_slug', '-price_xof'], name='intelligenc_catalog_044584_idx'), models.Index(fields=['location_region', '-views_count'], name='intelligenc_locatio_4f6d89_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestJijiPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Négociable')),
                ('condition', models.CharField(blank=True, max_length=20, verbose_name='État')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Capturé le')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='intelligence.testjijilisting', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Snapshot prix Jiji (test)',
                'verbose_name_plural': 'Snapshots prix Jiji (test)',
                'db_table': 'intelligence_test_jiji_price_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='JijiPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Négociable')),
                ('condition', models.CharField(blank=True, max_length=20, verbose_name='État')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Capturé le')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='intelligence.jijilisting', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Snapshot prix Jiji',
                'verbose_name_plural': 'Snapshots prix Jiji',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['listing', '-captured_at'], name='intelligenc_listing_0cd3d6_idx')],
            },
        ),
    ]
