# Generated by Django 5.2.16 on 2026-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0022_jiji_marketplace_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsearchkeyword',
            name='max_videos',
            field=models.PositiveSmallIntegerField(default=15, help_text='TikTok : vidéos. Jumia : produits. Jiji : annonces scrapées.', verbose_name='Max vidéos TikTok / produits Jumia / annonces Jiji'),
        ),
    ]
