# Generated by Django 5.2.16 on 2026-07-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0025_unified_marketplace_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsearchkeyword',
            name='listing_page_offset',
            field=models.PositiveSmallIntegerField(default=1, help_text='Page de départ pour la prochaine collecte Jumia (évite de re-scraper les mêmes listings).', verbose_name='Page listing Jumia (rotation)'),
        ),
        migrations.CreateModel(
            name='TestJumiaHomepageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=500)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=400)),
                ('price_label', models.CharField(blank=True, max_length=64)),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('stock_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('section_label', models.CharField(blank=True, db_index=True, max_length=160)),
                ('matched_keyword', models.CharField(db_index=True, max_length=200)),
                ('keyword_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enriched', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Hit accueil Jumia (test)',
                'verbose_name_plural': 'Hits accueil Jumia (test)',
                'ordering': ['-scraped_at'],
                'constraints': [models.UniqueConstraint(fields=('product_url', 'matched_keyword'), name='unique_test_jumia_homepage_hit_kw')],
            },
        ),
        migrations.CreateModel(
            name='JumiaHomepageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField(max_length=500, verbose_name='URL produit')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=400, verbose_name='Nom')),
                ('price_label', models.CharField(blank=True, max_length=64, verbose_name='Prix affiché')),
                ('discount_percent', models.FloatField(blank=True, null=True, verbose_name='Remise %')),
                ('stock_remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock restant (accueil)')),
                ('section_label', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='Section accueil')),
                ('matched_keyword', models.CharField(db_index=True, max_length=200, verbose_name='Mot-clé matché')),
                ('enriched', models.BooleanField(default=False, help_text='True si la fiche produit + avis ont été collectés.', verbose_name='Fiche enrichie')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Repéré le')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jumia_homepage_hits', to='intelligence.marketsearchkeyword', verbose_name='Mot-clé Paramètres')),
            ],
            options={
                'verbose_name': 'Hit accueil Jumia',
                'verbose_name_plural': 'Hits accueil Jumia',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['matched_keyword', '-scraped_at'], name='intelligenc_matched_fb2619_idx'), models.Index(fields=['enriched', '-scraped_at'], name='intelligenc_enriche_734630_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_url', 'matched_keyword'), name='unique_jumia_homepage_hit_kw')],
            },
        ),
    ]
