# Generated by Django 5.2.16 on 2026-07-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0026_jumia_homepage_dedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsearchkeyword',
            name='listing_page_offset',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Page de départ pour la prochaine collecte Jumia/Jiji (rotation listings).',
                verbose_name='Page listing (rotation)',
            ),
        ),
        migrations.CreateModel(
            name='TestJijiHomepageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_url', models.URLField(max_length=500)),
                ('listing_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('title', models.CharField(max_length=400)),
                ('price_label', models.CharField(blank=True, max_length=64)),
                ('condition_label', models.CharField(blank=True, max_length=40)),
                ('location_label', models.CharField(blank=True, max_length=160)),
                ('seller_badge', models.CharField(blank=True, max_length=120)),
                ('section_label', models.CharField(blank=True, default='trending', max_length=160)),
                ('matched_keyword', models.CharField(db_index=True, max_length=200)),
                ('keyword_id', models.PositiveIntegerField(blank=True, null=True)),
                ('enriched', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Hit accueil Jiji (test)',
                'verbose_name_plural': 'Hits accueil Jiji (test)',
                'ordering': ['-scraped_at'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('listing_url', 'matched_keyword'),
                        name='unique_test_jiji_homepage_hit_kw',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='JijiHomepageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_url', models.URLField(max_length=500, verbose_name='URL annonce')),
                ('listing_id', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='ID annonce')),
                ('title', models.CharField(max_length=400, verbose_name='Titre')),
                ('price_label', models.CharField(blank=True, max_length=64, verbose_name='Prix affiché')),
                ('condition_label', models.CharField(blank=True, max_length=40, verbose_name='État affiché')),
                ('location_label', models.CharField(blank=True, max_length=160, verbose_name='Localisation')),
                ('seller_badge', models.CharField(blank=True, max_length=120, verbose_name='Badge vendeur')),
                ('section_label', models.CharField(blank=True, default='trending', max_length=160, verbose_name='Section accueil')),
                ('matched_keyword', models.CharField(db_index=True, max_length=200, verbose_name='Mot-clé matché')),
                ('enriched', models.BooleanField(default=False, verbose_name='Fiche enrichie')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Repéré le')),
                ('keyword', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='jiji_homepage_hits',
                    to='intelligence.marketsearchkeyword',
                    verbose_name='Mot-clé Paramètres',
                )),
            ],
            options={
                'verbose_name': 'Hit accueil Jiji',
                'verbose_name_plural': 'Hits accueil Jiji',
                'ordering': ['-scraped_at'],
                'indexes': [
                    models.Index(fields=['matched_keyword', '-scraped_at'], name='intelligenc_jiji_kw_idx'),
                    models.Index(fields=['enriched', '-scraped_at'], name='intelligenc_jiji_enr_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('listing_url', 'matched_keyword'),
                        name='unique_jiji_homepage_hit_kw',
                    ),
                ],
            },
        ),
    ]
