# Generated by Django 5.2.16 on 2026-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0027_jiji_homepage_dedup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jijihomepagehit',
            new_name='intelligenc_matched_e005b1_idx',
            old_name='intelligenc_jiji_kw_idx',
        ),
        migrations.RenameIndex(
            model_name='jijihomepagehit',
            new_name='intelligenc_enriche_00ab11_idx',
            old_name='intelligenc_jiji_enr_idx',
        ),
        migrations.AlterField(
            model_name='marketsearchkeyword',
            name='listing_page_offset',
            field=models.PositiveSmallIntegerField(default=1, help_text='Page de départ pour la prochaine collecte Jumia (évite de re-scraper les mêmes listings).', verbose_name='Page listing Jumia (rotation)'),
        ),
    ]
