# Generated by Django 5.2.16 on 2026-07-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0029_jiji_nlp_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(db_index=True, help_text='Copie du mot-clé — conservée même si le mot-clé Paramètres est supprimé.', max_length=200, verbose_name='Mot-clé (texte)')),
                ('product_slug', models.SlugField(blank=True, max_length=80, verbose_name='Slug produit')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom produit')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Date du snapshot')),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Rang du jour')),
                ('score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Score global (0-100)')),
                ('demand_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score demande (0-100)')),
                ('trend_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score tendance (0-100)')),
                ('competition_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score concurrence (0-100)')),
                ('price_score', models.PositiveSmallIntegerField(default=0, verbose_name='Score prix (0-100)')),
                ('decision', models.CharField(choices=[('buy', 'Acheter'), ('watch', 'Surveiller'), ('avoid', 'Éviter')], db_index=True, default='watch', max_length=8, verbose_name='Décision')),
                ('decision_reasons', models.JSONField(blank=True, default=list, help_text='Liste de phrases lisibles justifiant la décision.', verbose_name='Raisons de la décision')),
                ('market_price_min_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix min marché')),
                ('market_price_avg_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix moyen marché')),
                ('market_price_max_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix max marché')),
                ('jumia_sellers', models.PositiveIntegerField(default=0, verbose_name='Vendeurs Jumia distincts')),
                ('jiji_listings_count', models.PositiveIntegerField(default=0, verbose_name='Annonces Jiji')),
                ('purchase_intent_count', models.PositiveIntegerField(default=0, verbose_name="Intentions d'achat (7 j)")),
                ('total_views', models.PositiveBigIntegerField(default=0, verbose_name='Vues réseaux (7 j)')),
                ('stock_alert', models.CharField(blank=True, default='', help_text='watch | critical | vide', max_length=16, verbose_name='Alerte stock Jumia')),
                ('suggested_price_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente conseillé')),
                ('supplier_price_xof', models.DecimalField(blank=True, decimal_places=2, help_text='Phase 2 — prix Alibaba converti en FCFA.', max_digits=12, null=True, verbose_name='Prix fournisseur (FCFA)')),
                ('estimated_margin_percent', models.FloatField(blank=True, help_text='Phase 2 — (prix conseillé − coût import) / prix conseillé.', null=True, verbose_name='Marge estimée %')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': "Opportunité d'importation",
                'verbose_name_plural': "Opportunités d'importation",
                'ordering': ['-snapshot_date', 'rank'],
            },
        ),
        migrations.RenameIndex(
            model_name='jijilisting',
            new_name='intelligenc_is_anal_736b4d_idx',
            old_name='intel_jiji_nlp_idx',
        ),
        migrations.RenameIndex(
            model_name='jijilisting',
            new_name='intelligenc_is_agri_89d21e_idx',
            old_name='intel_jiji_agri_idx',
        ),
        migrations.AlterField(
            model_name='jijilisting',
            name='analysis_method',
            field=models.CharField(choices=[('keyword', 'Filtre mots-clés (FR/Wolof)'), ('camembert', 'CamemBERT zero-shot'), ('pending', 'En attente')], default='pending', max_length=16, verbose_name='Méthode analyse'),
        ),
        migrations.AlterField(
            model_name='jijilisting',
            name='intent',
            field=models.CharField(blank=True, choices=[('intention_achat', "Intention d'achat"), ('demande_information', "Demande d'information"), ('hors_sujet', 'Hors sujet'), ('plainte', 'Plainte')], db_index=True, max_length=32, verbose_name='Intention détectée'),
        ),
        migrations.AlterField(
            model_name='testjijilisting',
            name='analysis_method',
            field=models.CharField(choices=[('keyword', 'Filtre mots-clés (FR/Wolof)'), ('camembert', 'CamemBERT zero-shot'), ('pending', 'En attente')], default='pending', max_length=16, verbose_name='Méthode analyse'),
        ),
        migrations.AlterField(
            model_name='testjijilisting',
            name='intent',
            field=models.CharField(blank=True, choices=[('intention_achat', "Intention d'achat"), ('demande_information', "Demande d'information"), ('hors_sujet', 'Hors sujet'), ('plainte', 'Plainte')], db_index=True, max_length=32, verbose_name='Intention détectée'),
        ),
        migrations.AddField(
            model_name='importopportunity',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_opportunities', to='intelligence.marketsearchkeyword', verbose_name='Mot-clé Paramètres'),
        ),
        migrations.AddIndex(
            model_name='importopportunity',
            index=models.Index(fields=['snapshot_date', 'decision'], name='intelligenc_snapsho_a18c40_idx'),
        ),
        migrations.AddIndex(
            model_name='importopportunity',
            index=models.Index(fields=['snapshot_date', '-score'], name='intelligenc_snapsho_f3e259_idx'),
        ),
        migrations.AddConstraint(
            model_name='importopportunity',
            constraint=models.UniqueConstraint(fields=('snapshot_date', 'keyword_text'), name='unique_import_opportunity_per_day'),
        ),
    ]
