# Generated by Django 5.2.16 on 2026-07-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0030_import_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_slug', models.SlugField(max_length=80, verbose_name='Domaine (slug)')),
                ('domain_label', models.CharField(max_length=120, verbose_name='Domaine')),
                ('category_slug', models.SlugField(max_length=80, verbose_name='Catégorie (slug)')),
                ('category_label', models.CharField(max_length=120, verbose_name='Catégorie')),
                ('search_query', models.CharField(db_index=True, max_length=300, verbose_name='Requête de recherche')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('collecting', 'Collecte en cours'), ('analyzing', 'Analyse DeepSeek'), ('done', 'Terminé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Tâche Celery')),
                ('progress_message', models.CharField(blank=True, max_length=300, verbose_name='Message progression')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Progression %')),
                ('collect_payload', models.JSONField(blank=True, default=dict, verbose_name='Données collectées')),
                ('deepseek_web_context', models.TextField(blank=True, verbose_name='Contexte web DeepSeek')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='Résultat analyse')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Session recherche marché',
                'verbose_name_plural': 'Sessions recherche marché',
                'ordering': ['-created_at'],
            },
        ),
    ]
