# Generated by Django 5.2.16 on 2026-07-29 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0031_market_research_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketresearchsession',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_sessions', to='intelligence.marketdomain', verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='marketresearchsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(10, '10 mn'), (20, '20 mn'), (30, '30 mn'), (60, '1 H'), (120, '2 H'), (180, '3 H'), (240, '4 H'), (300, '5 H')], default=20, verbose_name='Durée max (minutes)'),
        ),
        migrations.AddField(
            model_name='marketresearchsession',
            name='keyword',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Mot-clé'),
        ),
        migrations.AddField(
            model_name='marketresearchsession',
            name='sources',
            field=models.JSONField(blank=True, default=list, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='marketresearchsession',
            name='category_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='marketresearchsession',
            name='category_slug',
            field=models.SlugField(blank=True, max_length=80, verbose_name='Catégorie (slug)'),
        ),
        migrations.AlterField(
            model_name='marketresearchsession',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('collecting', 'Collecte en cours'), ('analyzing', 'Analyse DeepSeek'), ('done', 'Terminé'), ('failed', 'Échec'), ('stopped', 'Arrêté (analyse)')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
