# Generated by Django 5.2.16 on 2026-07-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0032_market_research_session_keyword_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportMasterDomainAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, default='', max_length=300)),
                ('domains_snapshot', models.JSONField(blank=True, default=list)),
                ('web_context', models.TextField(blank=True, default='')),
                ('analysis_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analyse Import Master domaines',
                'verbose_name_plural': 'Analyses Import Master domaines',
                'ordering': ['-created_at'],
            },
        ),
    ]
