# Generated by Django 5.2.16 on 2026-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0033_import_master_domain_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importmasterdomainanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec'), ('stopped', 'Arrêtée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketresearchsession',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('collecting', 'Collecte en cours'), ('analyzing', 'Analyse IA'), ('done', 'Terminé'), ('failed', 'Échec'), ('stopped', 'Arrêté (analyse)')], db_index=True, default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
