# Generated by Django 5.2.16 on 2026-08-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0034_alter_importmasterdomainanalysis_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumiaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('path', models.CharField(help_text='Ex. /telephones-tablettes/', max_length=200, unique=True, verbose_name='Chemin URL')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL complète')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='Nb produits')),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier crawl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='intelligence.jumiacategory', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie Jumia',
                'verbose_name_plural': 'Catégories Jumia',
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='jumiaproduct',
            name='jumia_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='intelligence.jumiacategory', verbose_name='Catégorie catalogue'),
        ),
    ]
